### PR TITLE
Use fonttools to compress/optimize the fonts.

### PR DESCRIPTION
**Pull request by fred-wang**
cc @khaledhosny

This is an attempt to do https://github.com/fred-wang/MathFonts/issues/3#issuecomment-174165737

A quick test gives ~10kb win for math fonts. I also get python errors for Libertinus/XITS (I need to check that). I'm not sure what's the recommended parameters for pyftsubset...

### CODE REVIEW

**Comment by khaledhosny** [comment]
If you only want FontTools’ more efficient OT code without changing anything, it would be better to just decode the font with `ttx` and encoding it again (or using a dedicated python script to avoid the need to write XML to disk first).

**Comment by fred-wang** [comment]
Thanks, I go with a python script.

**Comment by fred-wang** [comment]
Done in https://github.com/fred-wang/MathFonts/commit/ae90c1131d1fec20648983e483c4e2eacd5a7c53

**Comment by fred-wang** [comment]
The result of direct conversion (old) and conversion via fonttool (new) is essentially the same (< 1kb of difference). Maybe I'm doing something wrong.


    +--------------------------------+------+------+
    |Font                            | old  | new  |
    +--------------------------------+------+------+
    |Asana-Math.woff                 |303952|304032|
    +--------------------------------+------+------+
    |Asana-Math.woff2                |252180|252288|
    +--------------------------------+------+------+
    |latinmodern-math.woff           |483524|483808|
    +--------------------------------+------+------+
    |latinmodern-math.woff2          |391572|391656|
    +--------------------------------+------+------+
    |libertinusmath-regular.woff     |433832|434752|
    +--------------------------------+------+------+
    |libertinusmath-regular.woff2    |350612|350848|
    +--------------------------------+------+------+
    |libertinusserif-bolditalic.woff |186924|187236|
    +--------------------------------+------+------+
    |libertinusserif-bolditalic.woff2|147928|147916|
    +--------------------------------+------+------+
    |libertinusserif-bold.woff       |241500|241852|
    +--------------------------------+------+------+
    |libertinusserif-bold.woff2      |191568|191364|
    +--------------------------------+------+------+
    |libertinusserif-italic.woff     |254428|254572|
    +--------------------------------+------+------+
    |libertinusserif-italic.woff2    |203048|202800|
    +--------------------------------+------+------+
    |libertinusserif-regular.woff    |301140|301944|
    +--------------------------------+------+------+
    |libertinusserif-regular.woff2   |241172|241548|
    +--------------------------------+------+------+
    |lmroman12-bold.woff             |54332 |54376 |
    +--------------------------------+------+------+
    |lmroman12-bold.woff2            |47056 |46972 |
    +--------------------------------+------+------+
    |lmroman12-italic.woff           |57048 |57088 |
    +--------------------------------+------+------+
    |lmroman12-italic.woff2          |49520 |49504 |
    +--------------------------------+------+------+
    |lmroman12-regular.woff          |54320 |54364 |
    +--------------------------------+------+------+
    |lmroman12-regular.woff2         |47088 |46968 |
    +--------------------------------+------+------+
    |texgyrebonum-bolditalic.woff    |75868 |75892 |
    +--------------------------------+------+------+
    |texgyrebonum-bolditalic.woff2   |63428 |63648 |
    +--------------------------------+------+------+
    |texgyrebonum-bold.woff          |72720 |72752 |
    +--------------------------------+------+------+
    |texgyrebonum-bold.woff2         |60888 |60788 |
    +--------------------------------+------+------+
    |texgyrebonum-italic.woff        |76076 |76084 |
    +--------------------------------+------+------+
    |texgyrebonum-italic.woff2       |63472 |63512 |
    +--------------------------------+------+------+
    |texgyrebonum-math.woff          |340608|340868|
    +--------------------------------+------+------+
    |texgyrebonum-math.woff2         |271356|271432|
    +--------------------------------+------+------+
    |texgyrebonum-regular.woff       |72864 |72872 |
    +--------------------------------+------+------+
    |texgyrebonum-regular.woff2      |61280 |61256 |
    +--------------------------------+------+------+
    |texgyrepagella-bolditalic.woff  |77300 |77304 |
    +--------------------------------+------+------+
    |texgyrepagella-bolditalic.woff2 |64996 |64864 |
    +--------------------------------+------+------+
    |texgyrepagella-bold.woff        |75976 |75992 |
    +--------------------------------+------+------+
    |texgyrepagella-bold.woff2       |63092 |63028 |
    +--------------------------------+------+------+
    |texgyrepagella-italic.woff      |78496 |78508 |
    +--------------------------------+------+------+
    |texgyrepagella-italic.woff2     |64952 |65028 |
    +--------------------------------+------+------+
    |texgyrepagella-math.woff        |374816|375092|
    +--------------------------------+------+------+
    |texgyrepagella-math.woff2       |301384|301648|
    +--------------------------------+------+------+
    |texgyrepagella-regular.woff     |76052 |76068 |
    +--------------------------------+------+------+
    |texgyrepagella-regular.woff2    |62964 |63016 |
    +--------------------------------+------+------+
    |texgyreschola-bolditalic.woff   |76688 |76704 |
    +--------------------------------+------+------+
    |texgyreschola-bolditalic.woff2  |63636 |63400 |
    +--------------------------------+------+------+
    |texgyreschola-bold.woff         |73532 |73548 |
    +--------------------------------+------+------+
    |texgyreschola-bold.woff2        |60952 |60924 |
    +--------------------------------+------+------+
    |texgyreschola-italic.woff       |75424 |75448 |
    +--------------------------------+------+------+
    |texgyreschola-italic.woff2      |62688 |62676 |
    +--------------------------------+------+------+
    |texgyreschola-math.woff         |393876|394112|
    +--------------------------------+------+------+
    |texgyreschola-math.woff2        |321984|322256|
    +--------------------------------+------+------+
    |texgyreschola-regular.woff      |72148 |72168 |
    +--------------------------------+------+------+
    |texgyreschola-regular.woff2     |60060 |59804 |
    +--------------------------------+------+------+
    |texgyretermes-bolditalic.woff   |76724 |76744 |
    +--------------------------------+------+------+
    |texgyretermes-bolditalic.woff2  |63404 |63336 |
    +--------------------------------+------+------+
    |texgyretermes-bold.woff         |73512 |73520 |
    +--------------------------------+------+------+
    |texgyretermes-bold.woff2        |61052 |61248 |
    +--------------------------------+------+------+
    |texgyretermes-italic.woff       |75864 |75884 |
    +--------------------------------+------+------+
    |texgyretermes-italic.woff2      |63600 |63652 |
    +--------------------------------+------+------+
    |texgyretermes-math.woff         |346524|346736|
    +--------------------------------+------+------+
    |texgyretermes-math.woff2        |276960|276756|
    +--------------------------------+------+------+
    |texgyretermes-regular.woff      |74260 |74276 |
    +--------------------------------+------+------+
    |texgyretermes-regular.woff2     |61536 |61664 |
    +--------------------------------+------+------+
    |xits-bolditalic.woff            |73400 |73420 |
    +--------------------------------+------+------+
    |xits-bolditalic.woff2           |61652 |61676 |
    +--------------------------------+------+------+
    |xits-bold.woff                  |98340 |98360 |
    +--------------------------------+------+------+
    |xits-bold.woff2                 |81732 |81540 |
    +--------------------------------+------+------+
    |xits-italic.woff                |76772 |76776 |
    +--------------------------------+------+------+
    |xits-italic.woff2               |65048 |64948 |
    +--------------------------------+------+------+
    |xits-mathbold.woff              |166808|166848|
    +--------------------------------+------+------+
    |xits-mathbold.woff2             |140972|140816|
    +--------------------------------+------+------+
    |xits-math.woff                  |352104|352232|
    +--------------------------------+------+------+
    |xits-math.woff2                 |295108|295288|
    +--------------------------------+------+------+
    |xits-regular.woff               |156492|156520|
    +--------------------------------+------+------+
    |xits-regular.woff2              |128316|128236|
    +--------------------------------+------+------+

**Comment by khaledhosny** [comment]
I didn’t try all the fonts, but here is what I git for Libertinus Math using `ttx`:
````
+--------------------------------+------+------+
| Font                           | Old  | New  |
+--------------------------------+------+------+
| libertinusmath-regular.otf     | 691K | 681K |
| libertinusmath-regular.woff    | 424K | 418K |
| libertinusmath-regular.woff2   | 343K | 339K |
+--------------------------------+------+------+
````

My guess is that you need to force FonTools to compile the tables, otherwise it will just use the compiled binary tables it read from the file unmodified. Something like:
```python
f =  TTFont(…)
for t in f.keys():
    if hasattr(f[t], "compile"):
        f[t].compile(f)
````

**Comment by fred-wang** [comment]
Thanks, that seems to give smaller sizes in general (I'm only checking the woff/woff2 fonts):

    +--------------------------------+------+
    |Asana-Math.woff                 |298048|
    +--------------------------------+------+
    |Asana-Math.woff2                |247828|
    +--------------------------------+------+
    |latinmodern-math.woff           |475584|
    +--------------------------------+------+
    |latinmodern-math.woff2          |390380|
    +--------------------------------+------+
    |libertinusmath-regular.woff     |428088|
    +--------------------------------+------+
    |libertinusmath-regular.woff2    |346920|
    +--------------------------------+------+
    |libertinusserif-bold.woff       |237604|
    +--------------------------------+------+
    |libertinusserif-bold.woff2      |189852|
    +--------------------------------+------+
    |libertinusserif-bolditalic.woff |187236|
    +--------------------------------+------+
    |libertinusserif-bolditalic.woff2|147916|
    +--------------------------------+------+
    |libertinusserif-italic.woff     |254572|
    +--------------------------------+------+
    |libertinusserif-italic.woff2    |202800|
    +--------------------------------+------+
    |libertinusserif-regular.woff    |296748|
    +--------------------------------+------+
    |libertinusserif-regular.woff2   |239496|
    +--------------------------------+------+
    |lmroman12-bold.woff             |52820 |
    +--------------------------------+------+
    |lmroman12-bold.woff2            |46020 |
    +--------------------------------+------+
    |lmroman12-italic.woff           |55488 |
    +--------------------------------+------+
    |lmroman12-italic.woff2          |48536 |
    +--------------------------------+------+
    |lmroman12-regular.woff          |52812 |
    +--------------------------------+------+
    |lmroman12-regular.woff2         |46132 |
    +--------------------------------+------+
    |texgyrebonum-bold.woff          |70140 |
    +--------------------------------+------+
    |texgyrebonum-bold.woff2         |59388 |
    +--------------------------------+------+
    |texgyrebonum-bolditalic.woff    |73064 |
    +--------------------------------+------+
    |texgyrebonum-bolditalic.woff2   |62200 |
    +--------------------------------+------+
    |texgyrebonum-italic.woff        |73444 |
    +--------------------------------+------+
    |texgyrebonum-italic.woff2       |62128 |
    +--------------------------------+------+
    |texgyrebonum-math.woff          |333628|
    +--------------------------------+------+
    |texgyrebonum-math.woff2         |267972|
    +--------------------------------+------+
    |texgyrebonum-regular.woff       |70340 |
    +--------------------------------+------+
    |texgyrebonum-regular.woff2      |59832 |
    +--------------------------------+------+
    |texgyrepagella-bold.woff        |73600 |
    +--------------------------------+------+
    |texgyrepagella-bold.woff2       |61624 |
    +--------------------------------+------+
    |texgyrepagella-bolditalic.woff  |74968 |
    +--------------------------------+------+
    |texgyrepagella-bolditalic.woff2 |63440 |
    +--------------------------------+------+
    |texgyrepagella-italic.woff      |76020 |
    +--------------------------------+------+
    |texgyrepagella-italic.woff2     |63896 |
    +--------------------------------+------+
    |texgyrepagella-math.woff        |368108|
    +--------------------------------+------+
    |texgyrepagella-math.woff2       |297496|
    +--------------------------------+------+
    |texgyrepagella-regular.woff     |73452 |
    +--------------------------------+------+
    |texgyrepagella-regular.woff2    |61448 |
    +--------------------------------+------+
    |texgyreschola-bold.woff         |70812 |
    +--------------------------------+------+
    |texgyreschola-bold.woff2        |59736 |
    +--------------------------------+------+
    |texgyreschola-bolditalic.woff   |74020 |
    +--------------------------------+------+
    |texgyreschola-bolditalic.woff2  |62328 |
    +--------------------------------+------+
    |texgyreschola-italic.woff       |72816 |
    +--------------------------------+------+
    |texgyreschola-italic.woff2      |61376 |
    +--------------------------------+------+
    |texgyreschola-math.woff         |387640|
    +--------------------------------+------+
    |texgyreschola-math.woff2        |319640|
    +--------------------------------+------+
    |texgyreschola-regular.woff      |69540 |
    +--------------------------------+------+
    |texgyreschola-regular.woff2     |58384 |
    +--------------------------------+------+
    |texgyretermes-bold.woff         |70904 |
    +--------------------------------+------+
    |texgyretermes-bold.woff2        |59980 |
    +--------------------------------+------+
    |texgyretermes-bolditalic.woff   |74156 |
    +--------------------------------+------+
    |texgyretermes-bolditalic.woff2  |62428 |
    +--------------------------------+------+
    |texgyretermes-italic.woff       |73404 |
    +--------------------------------+------+
    |texgyretermes-italic.woff2      |62292 |
    +--------------------------------+------+
    |texgyretermes-math.woff         |339760|
    +--------------------------------+------+
    |texgyretermes-math.woff2        |273724|
    +--------------------------------+------+
    |texgyretermes-regular.woff      |71736 |
    +--------------------------------+------+
    |texgyretermes-regular.woff2     |60184 |
    +--------------------------------+------+
    |xits-bold.woff                  |98368 |
    +--------------------------------+------+
    |xits-bold.woff2                 |81852 |
    +--------------------------------+------+
    |xits-bolditalic.woff            |73428 |
    +--------------------------------+------+
    |xits-bolditalic.woff2           |61536 |
    +--------------------------------+------+
    |xits-italic.woff                |76764 |
    +--------------------------------+------+
    |xits-italic.woff2               |65020 |
    +--------------------------------+------+
    |xits-math.woff                  |352044|
    +--------------------------------+------+
    |xits-math.woff2                 |294944|
    +--------------------------------+------+
    |xits-mathbold.woff              |166812|
    +--------------------------------+------+
    |xits-mathbold.woff2             |140980|
    +--------------------------------+------+
    |xits-regular.woff               |156504|
    +--------------------------------+------+
    |xits-regular.woff2              |128232|
    +--------------------------------+------+

**Comment by fred-wang** [comment]
@khaledhosny So I actually still get errors with libertinus / xits using https://github.com/fred-wang/MathFonts/blob/master/compress-font.py :

- If I compress xits-math.otf and opens xits-math.woff with fontforge, I get many warnings "GID out of range (0) in format 14 'cmap' subtable"
- when compressing libertinus-italic.otf or libertinus-bolditalic.otf, I obtain the following python exception:

```
Traceback (most recent call last):
  File "../compress-font.py", line 22, in <module>
    if hasattr(font[t], "compile"):
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 403, in __getitem__
    table.decompile(data, self)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 45, in decompile
    self.table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 628, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 624, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 100, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 624, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 100, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 628, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 632, in decompile
    self.postRead(table, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otTables.py", line 54, in postRead
    (r.StartCoverageIndex, len(glyphs))
AssertionError: (35, 32)
Processing libertinusserif-bolditalic.otf => libertinusserif-bolditalic.woff
Traceback (most recent call last):
  File "../compress-font.py", line 22, in <module>
    if hasattr(font[t], "compile"):
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/__init__.py", line 403, in __getitem__
    table.decompile(data, self)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 45, in decompile
    self.table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 628, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 624, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 100, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 624, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 100, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 628, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otConverters.py", line 341, in read
    table.decompile(reader, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otBase.py", line 632, in decompile
    self.postRead(table, font)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/ttLib/tables/otTables.py", line 54, in postRead
    (r.StartCoverageIndex, len(glyphs))
AssertionError: (29, 26)
```

**Comment by khaledhosny** [comment]
The Libertinus issues are bugs in the fonts, I’m debugging this right now.

**Comment by khaledhosny** [comment]
The Libertinus issues should be fixed withh khaledhosny/libertinus@d9f93e86c3f029d151622698399a6b26e1a54215. The XITS Math issue sounds like a FontTools bug, even FontTools crashes opening the generated WOFF file.

**Comment by fred-wang** [comment]
Thanks, I'll check the XITS Math issue later again.

**Comment by fred-wang** [comment]
Apparently there is already an issue in fonttools: https://github.com/behdad/fonttools/issues/389

**Comment by khaledhosny** [comment]
I see, a quick fix is to skip `cmap` table from the compilation step, I don’t think there is much room for optimisation here (other than dropping redundant subtables of course, but FontTools will not do that automatically anyway).

**Comment by fred-wang** [comment]
Yes, that's what I thought too. I've done that and regenerated the fonts. I'm still using Libertinus 6.2 so the italic fonts fail to be generated but that's fine for now since the main goal of this repo are the math fonts.

**Comment by anthrotype** [comment]
@fred-wang the cmap's issue should be fixed with commit https://github.com/behdad/fonttools/commit/e40dffd86d62632c7643eaa3673503f15958f64d
please let me know if that's not the case.

**Comment by fred-wang** [comment]
@anthrotype Yes, it is fixed now. Thank you!

**Pull request closed without merging**
